### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by bheinks** [bheinks/cs2500_proj1#1]
- [x] Simulate AoI with sensors in initial states
- [x] Sensor intersection detection
- [x] Print AoI
- [x] Determine sensor coverage using Monte Carlo method
- [x] Implement redundancy algorithm
- [x] Implement selective activation algorithms
- [x] Simulate and update sensors after each round
- [ ] Integrate matplotlib for easy graphing
